### PR TITLE
Fix GCC7 warnings/errors

### PR DESCRIPTION
**Pull request by fepitre**
Fix GCC7 warnings/errors

### CODE REVIEW

**Comment by marmarek** [comment]
I have already merged it locally, but since it's too late to include it in 4.0rc2, I'll push it shortly after. In short: please don't push additional commits to this PR.

**Comment by fepitre** [comment]
No problem. Is there a way to ask github to stop adding commits ? I just merged the Qubes xen-4.8 branch into mine and it is adding your two last commits inside this pull request while it should not.

**Comment by marmarek** [comment]
Use separate branch for this.

**Comment by marmarek** [comment]
Since we're delaying rc2 anyway, I'll merge now.

**Pull request merged**
