### PR TITLE
Use %autosetup and prepare spec file for src.rpm

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by marmarek** [comment]
I wonder if its possible to still use separate directory for patches, otherwise the root directory gets quite messy... But it looks like it needs to be this way, for example Fedora kernel package: https://src.fedoraproject.org/rpms/kernel/tree/master

**Comment by fepitre** [comment]
Indeed, I had a look also to Fedora Xen and Kernel src.  I saw that e.g. we can use some lua code but I'm not sure that hacky things will help in the future. Otherwise, we could also add prefix to patches, like patches-qubes- patches-misc- or simply, qubes- misc- libxl- ... what do you think?

**Comment by marmarek** [comment]
Prefix would be some improvement. @HW42 any opinion?

**Comment by HW42** [comment]
Subdirectories would be of course preferable. I think I would go with a `patch-` prefix. And I would probably drop the qubes/misc/libxl split since the file name is already quite long and those categories are rather fuzzy anyway.

**Comment by HW42** [comment]
@fepitre are you sure `%autosetup` honors `series.conf`? The [rpm doc](http://rpm.org/user_doc/autosetup.html) @marmarek has linked only says "ordered by the patch number".

Anyway I think the patch numbering in this PR is confusing. If I have to add a new patch it would be tricky to find the next free number. Not sure what's the best solution. If manual numbered like currently probably a number block per comment block in `series.conf` would make sense. What about generating the patch list automatically based on `series.conf`? This would solve the numbering problem and avoid having to add a patch in two locations?

**Comment by marmarek** [comment]
> @fepitre are you sure %autosetup honors series.conf?

Definitely not. This PR even removes the file. Patch numbers (in xen.spec) are used.

> If manual numbered like currently probably a number block per comment block in series.conf would make sense.

Indeed that's better idea. 

> What about generating the patch list automatically based on series.conf? This would solve the numbering problem and avoid having to add a patch in two locations?

No-issue since there is no series.conf anymore (but there is still series-debian-vm.conf...).

**Comment by fepitre** [comment]
In fact I wrote a dumb script to generate the list of patches in the spec based on the series.conf. May be we could automate this to prevent doing twice time the job as you said. So we give up on separating patches in categories?

From what I read and tested it is apply as you said in order from the declared list of patches. I have tried to read as close as possible  what was applied before the build in the log and it seems ok. On any error it fails.

**Comment by HW42** [comment]
>> @fepitre are you sure %autosetup honors series.conf?
>
> Definitely not. This PR even removes the file. Patch numbers (in xen.spec) are used.

Oh, I was confused by the comment in PR #26 and the uncontinous numbering. As @fepitre wrote it seems the doc is wrong and it's the order the `.spec` and not the numbering which determines application ordering.

>> What about generating the patch list automatically based on series.conf? This would solve the numbering problem and avoid having to add a patch in two locations?
>
> No-issue since there is no series.conf anymore (but there is still series-debian-vm.conf...).

OTOH `series.conf` is understood by quilt. So autogenerating the patch list in in the `.spec` might still make sense.

**Comment by marmarek** [comment]
The main reason for this PR is to have as no-magic spec as possible. We will have `spec.in` files, but right now the plan is to use it only for version + release substitution, not anything fancy. The actual output spec file needs to be static and self contained (=parsing it should not depend on other files/patches/sources etc), otherwise resulting src.rpm package will be broken.

**Comment by HW42** [comment]
Well ok, then it's fine as-is.

**Comment by fepitre** [comment]
So what about the out of tree patches I keep the choice of numbering or I do all in one list linearly numbered?

And I add the prefix patch- in front?

**Comment by marmarek** [comment]
I'd add `patch-` prefix. And the idea of numbering them according to section in xen.spec (old series.conf) instead of old directory seems better. Reserve some numbers for security fixes (currently empty section).

**Comment by fepitre** [comment]
One question, # TODO? patches.libxl/xen-libxl-stubdom-pci-create.patch
where this patch should be with? in upstreamable patches?

**Comment by fepitre** [comment]
@marmarek @HW42 does this format https://gist.github.com/fepitre/196f1ad9aa22018e8a70dae681ca4d1e is ok for you?

**Comment by HW42** [comment]
> One question, # TODO? patches.libxl/xen-libxl-stubdom-pci-create.patch where this patch should be with? in upstreamable patches?

Probably yes. BTW I think we can just drop it. It has been unused for a long time and it's in the git history anyway.

> @marmarek @HW42 does this format https://gist.github.com/fepitre/196f1ad9aa22018e8a70dae681ca4d1e is ok for you?

Looks good to me.

**Comment by fepitre** [comment]
Ok. Thank you. I will redone the commit according to what is in the gist and I will remove the patches.libxl/xen-libxl-stubdom-pci-create.patch.

**Comment by fepitre** [comment]
I updated things according to what discussed.

**Comment by marmarek** [comment]
Thanks!

**Comment by fepitre** [comment]
You're welcome

**Pull request merged**
