### PR TITLE
add R coreutils to fix initial post install action

### PR DESCRIPTION
**Pull request by jevank**
This fixes missing xen.efi while OS setup

### CODE REVIEW

**Comment by marmarek** [comment]
Do you have a log of such failed install (especially package installation order)? It looks weird to have shell but not coreutils available at that time...

**Comment by jevank** [comment]
Sure, but tomorrow from lab laptop. Reproduced 3 in 3 today

**Comment by jevank** [comment]
Take a look

https://gist.github.com/jevank/6d58777f8c644a8888ab202113d74ca0#file-packaging-log-L522-L526

**Comment by marmarek** [comment]
Interesting. Anyway, in this case, we may need `gawk` dependency there too.

**Comment by jevank** [comment]
Looks like that is not critical in case initial setup - no efi record yet, but I could add it too.

**Pull request merged**
