### PR TITLE
Add Qubes Builder v2 integration

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry+head

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry+head

**Comment by fepitre** [comment]
PipelineRetry+head

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by fepitre** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
@fepitre tarball isn't copied in the right place:
```
19:44:13,668 [executor:docker:0b41354348] output: DEBUG: Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/xen.spec'] with env (...) and shell False
19:44:13,777 [executor:docker:0b41354348] output: DEBUG: error: Bad source: /builddir/build/SOURCES/xen-4.14.5.tar.gz: No such file or directory
```
I can see it in `artifacts/distfiles`

**Comment by marmarek** [comment]
nvm, it's about the version

**Pull request merged**
