### PR TITLE
IGD passthrough fix

### PR DESCRIPTION
**Pull request by cytadela8**
Xen part of @gorbak25 IGD passtrhough fixes

Qemu part: https://github.com/QubesOS/qubes-vmm-xen-stubdom-linux/pull/29

### CODE REVIEW

**Comment by marmarek** [comment]
Has this been sent to xen-devel already? I think it is too late to have it in Xen 4.14, but a review from xen maintainers would be useful anyway (and then, have it included in Xen 4.15).

**Comment by gorbak25** [comment]
> Has this been sent to xen-devel already? I think it is too late to have it in Xen 4.14, but a review from xen maintainers would be useful anyway (and then, have it included in Xen 4.15).
Those patches require linux based stubdomains. I don't think we can upstream them before linux based stubdomain are upstreamed to xen.

**Comment by marmarek** [comment]
Actually, we've managed to upstream libxl part, it's already committed to the Xen's master branch :)

**Comment by marmarek** [comment]
Also, ENOSYS -> EOPNOTSUPP looks like a separate pure-bugfix patch.

**Comment by marmarek** [comment]
Merged into xen-4.14 branch

**Pull request closed without merging**
