### PR TITLE
Use Linux’s PAT

### PR DESCRIPTION
**Pull request by DemiMarie**
Hopefully this will work around an i915 problem.

### CODE REVIEW

**Comment by marmarek** [comment]
IT WORKS!!!!!

**Comment by marmarek** [comment]
Are there any functional differences compared to 4.17's version, or just more cleanups there?

**Comment by DemiMarie** [comment]
> Are there any functional differences compared to 4.17's version, or just more cleanups there?

Theoretically there should be no functional difference, but much of that version has gone through upstream code review while this has not.  I would prefer to backport the upstreamed patches where possible.

**Comment by DemiMarie** [comment]
PipelineRetryFailed

**Comment by DemiMarie** [comment]
@fepitre what is causing the reproducable build failure?

**Comment by marmarek** [comment]
I think it's time to update the description to "workaround for broken i915 driver" instead of "purely for testing"...

**Comment by marmarek** [comment]
openQArun

**Comment by marmarek** [comment]
openQArun

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
openQArun

**Review by marmarek — APPROVED** [review]

**Pull request merged**
