### PR TITLE
add patch to additional support in ACPI builder SLIC and OEM installs

### PR DESCRIPTION
**Pull request by jevank**
This patch from OpenXT to update OEM and OEM ID signatures if SLIC table was defined. It is necessary to activate OEM media installed Windows.

### CODE REVIEW

**Comment by marmarek** [comment]
How is it enabled? It should be a opt-in feature - not enabled by default for privacy reasons.

**Comment by marmarek** [comment]
Oh, I should have waited for the other PR.

**Comment by jevank** [comment]
https://github.com/QubesOS/qubes-issues/issues/5279

**Comment by marmarek** [comment]
Please add `Signed-off-by` line (see https://developercertificate.org/). This way I'll be able to send it upstream.

**Comment by jevank** [comment]
This patch is from OpenXT repos with GPLv2 and MIT license as I see. Should I just add signed-off string at the end of description or count authors or smth else?... I`m a member of openxt team... so complicated..

**Comment by marmarek** [comment]
Hmm, if that's unmodified patch from OpenXT, then I think your S-o-b isn't needed (points b+c).

**Comment by jevank** [comment]
https://github.com/OpenXT/xenclient-oe/blob/master/recipes-extended/xen/files/acpi-slic-support.patch

**Comment by jevank** [comment]
I did nothing with it, it works fine

**Pull request merged**
