### PR TITLE
XSA-273

### PR DESCRIPTION
**Pull request by HW42**
https://github.com/QubesOS/qubes-intel-microcode/pull/3 is needed to actually use the new `L1D_FLUSH` function.

### CODE REVIEW

**Comment by rustybird** [comment]
Dumb question: What's the command to generate .patch files with these kind of filenames?

**Comment by HW42** [comment]
The "speaking" part is done by `git format-patch`. The commit prefix I do by hand for small numbers of patches or with some ad-hoc bash in cases like these. From my bash history, edited for readability:

    git log --reverse --pretty=format:%H RELEASE-4.8.4..d95b5bb31e6d4361e356f0ff0853b6bb172a8b6a > ~/tmp/xsa273-commits
    mkdir ~/tmp/xsa273-patches
    : > ~/tmp/xsa273-patches/series
    for i in $(<~/tmp/xsa273-commits); do
        rm -f ~/tmp/patch-export/*
        git format-patch -o ~/tmp/patch-export/ ${i}^..$i
        n=$(ls ~/tmp/patch-export | cut -c 6-)
        mv ~/tmp/patch-export/0001-$n ~/tmp/xsa273-patches/patch-${i:0:8}-$n
        echo patch-${i:0:8}-$n >> ~/tmp/xsa273-patches/series
    done

**Comment by rustybird** [comment]
Thanks! I can reproduce identical patch files (except for [patch-5464d5f0-x86-spec-ctrl-CPUID-MSR-definitions-for-L1D_FLUSH.patch](https://gist.githubusercontent.com/rustybird/f5b46354222df84c357a19d79739b9a2/raw/11af8c3d23be81b46c29eca15e0b8a481e3808e9/patch-5464d5f0-x86-spec-ctrl-CPUID-MSR-definitions-for-L1D_FLUSH.patch), which only has different context lines in libxl_cpuid.c) with git 2.18.0.

Maybe patch-4aec0c7f-update-Xen-version-to-4.8.5-pre.patch should be dropped if the Qubes package version is going to stay at `4.8.4-<rel>`?

**Comment by HW42** [comment]
> Thanks! I can reproduce identical patch files (except for [patch-5464d5f0-x86-spec-ctrl-CPUID-MSR-definitions-for-L1D_FLUSH.patch](https://gist.githubusercontent.com/rustybird/f5b46354222df84c357a19d79739b9a2/raw/11af8c3d23be81b46c29eca15e0b8a481e3808e9/patch-5464d5f0-x86-spec-ctrl-CPUID-MSR-definitions-for-L1D_FLUSH.patch), which only has different context lines in libxl_cpuid.c) with git 2.18.0.

That's because I manually fixed the context. The fix was so small that I didn't put in a separate commit, as I usally do for bigger fixes.

> Maybe patch-4aec0c7f-update-Xen-version-to-4.8.5-pre.patch should be dropped if the Qubes package version is going to stay at `4.8.4-<rel>`?

Since we are using 4.8.4 + all patches from staging up to the commit from the XSA, I think leaving it in is better since this matches more closely the upstream version. I will leave the decision whether the package version should be bumped to @marmarek or whoever will merge this.

**Comment by marmarek** [comment]
> Since we are using 4.8.4 + all patches from staging up to the commit from the XSA, I think leaving it in is better since this matches more closely the upstream version. I will leave the decision whether the package version should be bumped to @marmarek or whoever will merge this.

I'd drop that patch (staying at 4.8.4), if for nothing else, to avoid problems with version sorting (when final 4.8.5 got released).

**Comment by marmarek** [comment]
There is one catch: if PV guest kernel isn't updated, the mitigation may crash the guest on attempt to use swap as we have compiled out shadow paging (in R4.0). I've been testing this for some time and managed to trigger the crash once (using stock Fedora, unpatched kernel in PV guest, using pvgrub). This means we should at least include guest kernel update as part of security fix (I'm on it). While default configuration use PVH domains almost entirely (besides stubdomains, but those don't have swap), it is still possible to explicitly force PV domain and we should cover this in QSB too.
We have disabled shadow paging support for [the same reason as moving to PVH](https://www.qubes-os.org/news/2016/07/21/new-hw-certification-for-q4/). 

If crash happens anyway (xl dmesg message: `dXX L1TF-vulnerable L1e ... - Crashing`), it probably means given kernel wasn't updated (for example Debian jessie still doesn't have updated kernel available). I'd recommend switching to dom0-provided kernel in such case (and probably back to PVH mode).
Any better idea?

This problem doesn't apply to R3.2, as we have shadow paging support there enabled.

**Comment by HW42** [comment]
>  Any better idea?

Not really, but I would mention that disabling swap also helps as this also might be a acceptable solution in some cases.

**Comment by rustybird** [comment]
I just installed Qubes from a freshly built `release4.0` branch ISO (i.e. with Xen 4.8.4-2), and noticed that `smt=off` was not appended to the GRUB configuration. Maybe [`/etc/default/grub` does not exist yet](https://github.com/QubesOS/qubes-vmm-xen/pull/45/commits/3f010e939a0f62beb59cc13fc7040e1c9b0127c8#diff-94ae88f932653f6d4c35ff3a6600249cR795) when the hypervisor package is installed for the first time?

**Comment by marmarek** [comment]
That's very likely, thanks for the report!

**Pull request merged**
