### PR TITLE
stubdom-linux: Pass cmdline to stubdom via xenstore

### PR DESCRIPTION
**Pull request by HW42**

### CODE REVIEW

**Comment by marmarek** [comment]
When I'm looking at this patch, wouldn't it be better to put -append option directly to qemu arguments, like in dom0-qemu case? Will it handle spaces in kernelopts correctly?

**Comment by HW42** [comment]
> When I'm looking at this patch, wouldn't it be better to put -append option directly to qemu arguments, like in dom0-qemu case? Will it handle spaces in kernelopts correctly?

`libxl__write_stub_dmargs()` just joins the args with spaces and then write it to xenstore. So space separated arguments can't work. Now that I'm looking at, one option would be to shell escape the args and eval it in the stubdom.

**Comment by marmarek** [comment]
You mean in `libxl__write_stub_dmargs()`?

**Comment by HW42** [comment]
Yes.

**Comment by marmarek** [comment]
Ok.

**Comment by HW42** [comment]
So you would prefer escaping it in `libxl__write_stub_dmargs()` to the current solution with a separate xenstore key, right?

**Comment by marmarek** [comment]
Yes, IMO would be more flexible.

**Comment by marmarek** [comment]
Any update on this?

**Comment by HW42** [comment]
The cmdline passing is implemented (just pushed the updated version). I didn't like the eval so I used '\x1b' (ESC) as separator. This should never appear in a kernel command line.

But depending on the passed command line and the attached pci device QEMU crashes after attaching the PCI device ...

I did not tracked down the error yet. Probably something about the memory setup for passing the cmdline and/or the pci memory regions is broken.

**Comment by marmarek** [comment]
At least xenstore-client patch deserve sending upstream.

**Comment by marmarek** [comment]
I wonder how changing a way how kernel parameters are passed could cause qemu crash... Have you verified the same arguments passed the old way (cmdline.txt) do not cause the crash?

**Comment by HW42** [comment]
> I wonder how changing a way how kernel parameters are passed could cause qemu crash... Have you verified the same arguments passed the old way (cmdline.txt) do not cause the crash?

It's not the way how the cmdline is passed which causes the crash (and yes using the old method also triggers the crash). But since we never used the old method we always passed the hardcoded default cmdline which does not trigger it (I think it's the length).

Also the crash disappears after applying the (seemingly unrelated) commit QubesOS/qubes-vmm-xen-stubdom-linux@4675f10f7022b67e2a06444f540947ae21f380de. So the rebased version of QubesOS/qubes-vmm-xen-stubdom-linux#6 does not trigger the crash (at least for me). Nonetheless we should fix it. It probably will reappear as randomly.

**Comment by HW42** [comment]
Rebased the kernelopts PRs onto the latest versions. Should be merged after QubesOS/qubes-vmm-xen-stubdom-linux#7 (for some reason QEMU crashes only with longer cmdlines).

**Pull request merged**
