### PR TITLE
Add "stage 1" PTI patches against Meltdown

### PR DESCRIPTION
**Pull request by HW42**
From XSA 254 v9.

That's an alternative option to QubesOS/qubes-core-admin#178

The performance penalty seems to be **roughly** 20..25 %. Will post detailed numbers later.

### CODE REVIEW

**Comment by HW42** [comment]
Ok, here my performance test from last night.

**Warning**: Please keep in mind that that's an ad-hoc test I came up with yesterday. So take the result with a good grain of salt and read the note below about the guessed accuracy of the used tests.


## Test system

CPU: i5-3340M
RAM: 8 GiB (2x 4 GiB DDR3 1600 MHz)
Disk: SK hynix SH920 2.5 7MM 512GB

OS: Qubes R3.2
Template: fedora-26
VCPUs for test VM: 4

## Xen configs

 - [4.6.6-noxpti](https://github.com/QubesOS/qubes-vmm-xen/commit/0fec25fa32b751135029699ae025f8e82d8bfe7f) (official packages)
 - [4.6.6-xpti](https://github.com/HW42/qubes-vmm-xen/commit/84e55c075f0cded44d220ac86f41f39acb1f7ef6) (my build)

 - [4.8.2-noxpti](https://github.com/HW42/qubes-vmm-xen/commit/016dc3583bca1042f79c0f10584478a884901fa1) (my build)
 - [4.8.2-xpti](https://github.com/HW42/qubes-vmm-xen/commit/ca6e3eb87c78cb802a77706c1e227987b6a5760e) (my build)

## Tests

### VM startup

Start the VM once to warm up caches. Then average over 5 VM startups (`time qvm-run -a -p vm uptime`).

### Linux build

Build time of a small Linux kernel (Linux 4.14.12, `time (rm -rf linux-4.14.12 && tar xf linux-4.14.12.tar.xz && cd linux-4.14.12 && make defconfig && make xenconfig && make -j4)`).

### Speedometer 2.0

Run a [local copy](https://git.webkit.org/?p=WebKit.git;a=tree;f=PerformanceTests/Speedometer;hb=refs/heads/master) of [Speedometer 2.0](http://browserbench.org/Speedometer2.0/) in Firefox (57.0.1 (Fedora 26)).

The result is in runs per minutes. So keep in mind that this is the only test where **higher values are better**.

### Accuracy

I tried to guess the accuracy of those tests by re-running some of them. For PV domains the results seems to be reasonable (given the easy setup), less than 5 % difference between runs.

For PVH and HVM domains for some reason the startup and build time fluctuates heavily (10..30 %). So those results are meaningless for the observed difference (highlighted in italicts in the table below). The Speedometer results seem to be better (similar to the PV behavior).

## Results

### Xen 4.6

||VM startup [s]|Linux build [s]|Speedometer 2.0 [1/min]|
|:---|---:|---:|---:|
|4.6.6-noxpti|10.09|657.45|31.55|
|4.6.6-xpti|13.90|828.41|25.83|
|diff [%]|38|26|-18|

### Xen 4.8

||VM startup [s]|Linux build [s]|Speedometer 2.0 [1/min]|
|:---|---:|---:|---:|
|||||
|**PV**||||
|4.8.2-noxpti|9.94|668.01|31.15|
|4.8.2-xpti|13.41|841.56|24.80|
|diff [%]|35|26|-20|
|||||
|**PVH**||||
|4.8.2-noxpti|_12.58_|_858.25_|27.44|
|4.8.2-xpti|_13.34_|_945.13_|27.09|
|diff [%]|_6_|_10_|-1|
|||||
|**HVM**||||
|4.8.2-noxpti|_16.14_|_999.85_|26.78|
|4.8.2-xpti|_18.92_|_940.22_|26.39|
|diff [%]|_17_|_-6_|-1|

### Summary

So as I already wrote **roughly** 20..30 % worse than without XPTI for PV mode. No measurable effect on PVH/HVM.

**Comment by marmarek** [comment]
It is interesting why there is such a difference between PVH and PV on 4.8.2-noxpti. I'd expect those to be very close. Can you disable KPTI inside VM?

**Comment by HW42** [comment]
Can't measure any difference between an PVH domain with or without `nopti` on the command line (but `dmesg` reports the expected state for PTI).

BTW: Any idea why the PVH/HVM values fluctuate so much?

**Comment by marmarek** [comment]
No idea, but I see the same. Consecutive PVH startups on my machine are in 11-14s range

**Comment by marmarek** [comment]
> Can't measure any difference between an PVH domain with or without nopti on the command line (but dmesg reports the expected state for PTI).

Ok, so this basically means that "performance" argument for using PVH instead of PTI in R3.2 is mute.

**Pull request merged**
