### PR TITLE
Add BTI mitigation patches from XSA 254

### PR DESCRIPTION
**Pull request by HW42**
With the patches Xen reports that it's using `RETPOLINE` and `RSB_{NATIVE,VMEXIT}`.

I tried to load the Intel microcode updates from 2018-01-08 via Xen early microcode update on my Lenovo X1 Carbon (Kaby Lake CPU). But even though Xen loads the microcode it still doesn't report any hardware features.

AFAIK Intel currently recommends against using this microcode and an update isn't available yet, so I think we can merge this as-is, anyway.

Depends on https://github.com/HW42/qubes-gcc

### CODE REVIEW

**Comment by marmarek** [comment]
> Depends on https://github.com/HW42/qubes-gcc

Building for 4.0 now, 7.5h and counting...

**Comment by HW42** [comment]
Do you still see new output? If yes, keep waiting. I think for me it needed something about 9 h 45 min ...

**Comment by marmarek** [comment]
There is constantly new output in tests suite log.

**Comment by HW42** [comment]
Ok, this sounds fine. As I wrote it seems to be normal that a bunch of tests fail ... So I could have disabled the test to save time, but that would have required another test build ;/

**Comment by marmarek** [comment]
Oh great, build log upload (to https://github.com/qubesos/build-logs repo) failed, because its 120MB.
There are some not packaged files, is that ok, or you want a list?

**Comment by HW42** [comment]
I didn't change anything regarding what files are packaged. So this should be fine. I got this list:

    warning: Installed (but unpackaged) file(s) found:
       /usr/bin/gcov-dump
       /usr/lib/gcc/x86_64-redhat-linux/6.4.1/include-fixed/README
       /usr/lib/gcc/x86_64-redhat-linux/6.4.1/include-fixed/X11/Xw32defs.h
       /usr/lib/gcc/x86_64-redhat-linux/6.4.1/include-fixed/openssl/bn.h
       /usr/lib/gcc/x86_64-redhat-linux/6.4.1/include/ssp/ssp.h
       /usr/lib/gcc/x86_64-redhat-linux/6.4.1/include/ssp/stdio.h
       /usr/lib/gcc/x86_64-redhat-linux/6.4.1/include/ssp/string.h
       /usr/lib/gcc/x86_64-redhat-linux/6.4.1/include/ssp/unistd.h
       /usr/lib/gcc/x86_64-redhat-linux/6.4.1/install-tools/fixinc_list
       /usr/lib/gcc/x86_64-redhat-linux/6.4.1/install-tools/gsyslimits.h
       /usr/lib/gcc/x86_64-redhat-linux/6.4.1/install-tools/include/README
       /usr/lib/gcc/x86_64-redhat-linux/6.4.1/install-tools/include/limits.h
       /usr/lib/gcc/x86_64-redhat-linux/6.4.1/install-tools/macro_list
       /usr/lib/gcc/x86_64-redhat-linux/6.4.1/install-tools/mkheaders.conf
       /usr/lib/libcilkrts.spec
       /usr/lib/libgfortran.spec
       /usr/lib/libgomp.spec
       /usr/lib/libitm.spec
       /usr/lib/libmpx.spec
       /usr/lib/libsanitizer.spec
       /usr/lib64/libasan.so
       /usr/lib64/libatomic.so
       /usr/lib64/libcilkrts.so
       /usr/lib64/libgcc_s.so
       /usr/lib64/libgfortran.so
       /usr/lib64/libgo.so
       /usr/lib64/libgomp.so
       /usr/lib64/libitm.so
       /usr/lib64/liblsan.so
       /usr/lib64/libmpx.so
       /usr/lib64/libmpxwrappers.so
       /usr/lib64/libobjc.so
       /usr/lib64/libquadmath.so
       /usr/lib64/libstdc++.so
       /usr/lib64/libtsan.so
       /usr/lib64/libubsan.so
       /usr/libexec/gcc/x86_64-redhat-linux/6.4.1/install-tools/fixinc.sh
       /usr/libexec/gcc/x86_64-redhat-linux/6.4.1/install-tools/mkinstalldirs
       /usr/share/locale/de/LC_MESSAGES/libstdc++.mo
       /usr/share/locale/fr/LC_MESSAGES/libstdc++.mo
       /usr/share/man/man1/gcov-dump.1.gz
       /usr/share/man/man1/gcov-tool.1.gz
       /usr/share/man/man7/fsf-funding.7.gz
       /usr/share/man/man7/gfdl.7.gz
       /usr/share/man/man7/gpl.7.gz

**Comment by marmarek** [comment]
Looks similar.

**Comment by marmarek** [comment]
I'm trying to get travis use it: https://travis-ci.org/marmarek/qubes-vmm-xen/jobs/347588564
```
Error: package gcc-6.4.1-1.qubes1.fc25.x86_64 requires libgcc >= 6.4.1-1.qubes1.fc25, but none of the providers can be installed
```
Is it going to be this way until end of the days? Maybe we can add some dnf options to initial build env preparation? Note that env there was installed from scratch, for example I don't see any i686 package installed there.

**Comment by HW42** [comment]
Huh, the log is pretty strange. Just before it complaints about the missing `libgcc`:

    Error: package gcc-6.4.1-1.qubes1.fc25.x86_64 requires libgcc >= 6.4.1-1.qubes1.fc25, but none of the providers can be installed

It says it has installed it:

    Upgraded:
      kernel-devel.x86_64 1000:4.14.18-1.pvops.qubes                                
      libgcc.x86_64 6.4.1-1.qubes1.fc25                                             

One ugly option would be to fix by manually invoking `dnf install` in vmm-xen.

> Note that env there was installed from scratch, for example I don't see any i686 package installed there.

Yeah, this log looks like the problem is something else.

**Comment by marmarek** [comment]
DNF from fc26 gave slightly more detailed error:
```
 Problem: package gcc-6.4.1-1.qubes1.fc25.x86_64 requires libgcc_s.so.1, but none of the providers can be installed
  - libgcc-6.4.1-1.fc25.i686 has inferior architecture
  - libgcc-6.2.1-2.fc25.i686 has inferior architecture
  - cannot install both libgcc-6.4.1-1.qubes1.fc25.x86_64 and libgcc-6.4.1-1.fc25.x86_64
  - cannot install both libgcc-6.4.1-1.qubes1.fc25.x86_64 and libgcc-6.2.1-2.fc25.x86_64
  - cannot install the best update candidate for package libgcc-6.4.1-1.fc25.x86_64
  - cannot install the best update candidate for package gcc-6.4.1-1.fc25.x86_64
=======================================================================================================
 Package      Arch         Version                      Repository                                Size
=======================================================================================================
Upgrading:
 libgcc       x86_64       6.4.1-1.qubes1.fc25          qubes-builder-dom0-current-testing        95 k
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 libgcc       x86_64       6.2.1-2.fc25                 fedora                                    86 k
 libgcc       x86_64       6.4.1-1.qubes1.fc25          qubes-builder-dom0-current-testing        95 k
Skipping packages with broken dependencies:
 gcc          x86_64       6.4.1-1.qubes1.fc25          qubes-builder-dom0-current-testing        20 M
```
Still no idea what's wrong...

**Comment by marmarek** [comment]
Looking at gcc requirements I've found weird thing:
```diff
--- gcc-6.4.1-1.fc25-reqs.txt	2018-03-01 21:44:46.410836914 +0100
+++ gcc-6.4.1-1.qubes1.fc25-reqs.txt	2018-03-01 21:44:57.858836914 +0100
@@ -4,7 +4,7 @@
 /sbin/install-info
 /sbin/install-info
 binutils >= 2.24
-cpp = 6.4.1-1.fc25
+cpp = 6.4.1-1.qubes1.fc25
 glibc-devel >= 2.2.90-12
 isl = 0.14
 ld-linux-x86-64.so.2()(64bit)
@@ -19,10 +19,11 @@
 libc.so.6(GLIBC_2.4)(64bit)
 libdl.so.2()(64bit)
 libdl.so.2(GLIBC_2.2.5)(64bit)
-libgcc >= 6.4.1-1.fc25
+libgcc >= 6.4.1-1.qubes1.fc25
+libgcc_s.so.1
 libgcc_s.so.1()(64bit)
 libgmp.so.10()(64bit)
-libgomp = 6.4.1-1.fc25
+libgomp = 6.4.1-1.qubes1.fc25
 libgomp.so.1()(64bit)
 liblto_plugin.so.0()(64bit)
 libm.so.6()(64bit)
```
There is extra `libgcc_s.so.1` (without arch), and libgcc package does not provide this name.

**Comment by marmarek** [comment]
BTW looks like the whole problem does not apply to R3.2 build.

**Comment by HW42** [comment]
Ok, so there seem to be two things which pull in libgcc.i686:
  1. The new gcc packages requires libgcc_s.so.1 (didn't find yet why)
  2. xen.spec BuildRequires /usr/include/gnu/stubs-32.h which is provided by glibc-devel.i686 which requires libgcc(x86-32)

For R3.2, (1) is not the case (again don't know why) and glibc-devel.i686 does not require libgcc.i686 so (2) is not a problem.

**Comment by HW42** [comment]
PS: `rpmrebuild` is pretty useful for testing.

**Comment by marmarek** [comment]
Can we make dnf stop complaining about mismatching `libgcc{.i686,x86_64}` versions? For yum there was `protected_multilib=false` setting, but it isn't valid for dnf.

**Comment by HW42** [comment]
Is protected multilib only enforced sometimes? Because `dnf install gcc-6.4.1-1.qubes1.fc25.x86_64 libgcc-6.4.1-1.qubes1.fc25.x86_64` works, so it can't be a hard dependency requirement.

**Comment by marmarek** [comment]
Honestly I have no idea how it works in dnf. With you that would fail unless you set `protected_multilib=false`

**Comment by HW42** [comment]
I grepped around in the dnf/hawkey/libsolv sources but didn't found an option which sounds relevant ...

Maybe we just go the ugly way and call `dnf install ...` somewhere.

**Comment by marmarek** [comment]
Ok, [added it](https://github.com/marmarek/qubes-vmm-xen/commit/b79f692a2da10856f01c68eefbecbf5b1bcf8820). Seems to be [working](https://travis-ci.org/marmarek/qubes-vmm-xen/jobs/348080595#L1401-L1428).

**Comment by marmarek** [comment]
`hw42/sp2-4.6` branch is also ready for build, right?

**Comment by HW42** [comment]
> `hw42/sp2-4.6` branch is also ready for build, right?

It builds fine, but not really tested yet.

**Pull request merged**
