### PR TITLE
Few suspend-related fixes

### PR DESCRIPTION
**Pull request by marmarek**
Backport fix for suspend bug in credit2.
Workaround Windows PV drivers suspend bug.
Check for suspend support (for Mirage OS).

Fixes QubesOS/qubes-issues#6066
QubesOS/qubes-issues#7404

### CODE REVIEW

**Comment by marmarek** [comment]
> Workaround Windows PV drivers suspend bug.

Tested right now, and doing `virsh -c xen dompmsuspend` and `virsh -c xen dompmwakeup` twice on Windows 10 VM with QWT installed worked, both times.

**Comment by jevank** [comment]
> Tested right now, and doing virsh -c xen dompmsuspend and virsh -c xen dompmwakeup twice on Windows 10 VM with QWT installed worked, both times.

Did you get Windows 10 guest freeze because of clocksource? I still reproduce it.

**Comment by marmarek** [comment]
> Did you get Windows 10 guest freeze because of clocksource? I still reproduce it.

With suspending Windows (so, not excluding it anymore)?

**Comment by jevank** [comment]
Correct, I tried your working core-admin branch. I was confused that you successfully tested Windows 10 dompmsuspend. I have both systems with and without QWT freeze after first resume :-/

**Comment by marmarek** [comment]
I don't get the freeze anymore (I tested only without QWT - that one froze before). I can see see stubdomain suspend (`Freezing user space processes` etc messages on its console), but no clocksource switch, and no freeze.

**Pull request merged**
