### PR TITLE
R4.1: libxl: Add support for new qubes-gui options

### PR DESCRIPTION
**Pull request by HW42**

### CODE REVIEW

**Comment by HW42** [comment]
Depends on https://github.com/QubesOS/qubes-core-libvirt/pull/12.

**Comment by HW42** [comment]
>> Depends on QubesOS/qubes-core-libvirt#12.
>
> Why? Not the other way around?

I wrote this because this changes will break old libvirt versions. But you are right an explicit dependency is not required since the soname change will already take care of it.

> Also, you need to update Debian packaging after changing soname.

AFAICS it's only in `libxen-4.8.install` right?

Why is the soname hardcoded there instead of something like `.so.*` or `.so.4.8.*`?

Looking at it it might be a good idead to change the soname to `4.8-qubes2` or something similar to avoid confusion with the Xen version number. Do you know if this would create any problems?

**Comment by marmarek** [comment]
> AFAICS it's only in libxen-4.8.install right?

Yes.

> Why is the soname hardcoded there instead of something like .so.* or .so.4.8.*?

`.so.4.8.*` might be ok, but better not `.so.*`, to not include other other files in libxen-**4.8** package.

BTW changing soname without renaming Debian package might be problematic. AFAIR Debian do not automatically add dependencies based on soname (as rpm does), but only if explicitly specified ([debian policy](https://www.debian.org/doc/debian-policy/#shared-libraries), [example](https://github.com/QubesOS/qubes-linux-utils/blob/master/debian/libqubes-rpc-filecopy2.shlibs)). I don't think anything outsides of Xen Debian package links with libxl (in VM case), so it might be not a problem. But for bumping for example libxenvchan soname, it will be.
Upstream Debian package have pretty invasive patch which rename _all_ libraries to include `-4.8` in library name (not only soname), which suggests standard packaging rules and soname handling weren't enough for some reason.

> Looking at it it might be a good idead to change the soname to 4.8-qubes2 or something similar to avoid confusion with the Xen version number. Do you know if this would create any problems?

I'm not sure if letters are allowed. I haven't seen any library with letters in soname.

**Comment by marmarek** [comment]
Merged into xen-4.12 branch.

**Pull request closed without merging**
