### PR TITLE
Fix build on Archlinux

### PR DESCRIPTION
**Pull request by arjan-s**
Added Xen patch from
https://xenbits.xen.org/gitweb/?p=xen.git;a=commit;h=858dbaaeda33b05c1ac80aea0ba9a03924e09005
to fix compatibility with iasl >= 20180427

This fixes https://github.com/QubesOS/qubes-issues/issues/4026, but I don't know what it will do for other templates.

### CODE REVIEW

**Comment by marmarek** [comment]
The patch is already there: https://github.com/QubesOS/qubes-vmm-xen/blob/xen-4.8/patch-libacpi-fixes-for-iasl-20180427.patch
The missing part is listing it in series-vm.conf.

I wanted to use this occasion to plug Archlinux into Travis-CI to detect such problems earlier, but apparently it isn't such simple as environment used in Travis-CI is really ancient (Ubuntu 14.04) and some tools are too old: https://travis-ci.org/marmarek/qubes-vmm-xen/jobs/396185045
cc @ptitdoc

**Comment by arjan-s** [comment]
Thanks, I completely missed the existing patch. I've removed my duplicate and fixed series-vm.conf.

**Comment by sstt011** [comment]
@arjan-s you need to sign your code. See https://www.qubes-os.org/doc/code-signing/

**Comment by arjan-s** [comment]
Thanks. I'm going to look into that.

**Comment by marmarek** [comment]
After updating to 4.8.4 this patch isn't needed anymore (it's included in new upstream release).

**Pull request closed without merging**
