### PR TITLE
Add native xendriverdomain.service; remove cruft

### PR DESCRIPTION
**Pull request by rustybird**

### CODE REVIEW

**Comment by marmarek** [comment]
Thanks!

**Comment by rustybird** [comment]
Updated commit series force-pushed:

  - includes your (unchanged and signed) xl-devd-trigger commit
  - includes final version of xendriverdomain.service from Xen master
  - starts xl-devd-trigger with ExecStartPost=

**Comment by marmarek** [comment]
> starts xl-devd-trigger with ExecStartPost=

Actually, I'm just working on a patch to fix it correctly in `xl devd` itself :)

**Comment by rustybird** [comment]
Heh. Makes sense, removed it again here.

**Comment by marmarek** [comment]
I've merged previous version of this PR (before adding, then removing "starts xl-devd-trigger with ExecStartPost=").

**Pull request closed without merging**
